# Generated by Django 2.2.1 on 2019-05-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phono', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('Guests', models.IntegerField()),
            ],
        ),
    ]
