# Generated by Django 2.2.1 on 2019-05-19 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='phono',
            new_name='phone',
        ),
    ]
