# Generated by Django 2.2.1 on 2019-05-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risto', '0002_auto_20190519_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='time',
            field=models.IntegerField(),
        ),
    ]
