# Generated by Django 2.2.1 on 2019-05-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risto', '0003_auto_20190520_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='time',
            field=models.TimeField(),
        ),
    ]
