# Generated by Django 2.2.1 on 2019-05-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risto', '0004_auto_20190520_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='time',
            field=models.IntegerField(),
        ),
    ]
